### ISSUE TITLE
I don't know how to fix this.

### ISSUE THREAD

**Issue by Fourteenloving** [csjh/SkyblockSniper#12]
So I downloaded everything but got this when I launched it.
![242655185_738085107588699_1589306642613730266_n](https://user-images.githubusercontent.com/91829251/135751631-0d763940-7b13-4805-9db2-9bdeae56dc9d.jpg)

**Comment by csjh** [comment]
What does `python --version` return

**Comment by Fourteenloving** [comment]
i'm using 3.9.7 currently

**Comment by csjh** [comment]
> i'm using 3.9.7 currently

Is that what `python --version` returns?

And is that the only version of Python you have installed?

**Comment by Fourteenloving** [comment]
yes i only installed 3.9 on microsoft shop and 3.9.7 is the only version on there

**Comment by csjh** [comment]
Again, is that what python --version returns?

Was there any error when you did pip install?

Send a screenshot of your PATH system variables

**Comment by TheRealOmitron** [comment]
Go to command prompt and enter 
>pip install pandas

**Comment by Fourteenloving** [comment]
![image](https://user-images.githubusercontent.com/91829251/135778058-c0e0172e-c7b3-4526-b1c3-a5fd0d820b9c.png)
![image](https://user-images.githubusercontent.com/91829251/135778179-c7ade9fc-68bc-4482-8579-3877633142ec.png)
![image](https://user-images.githubusercontent.com/91829251/135778208-8db2f9b0-eeb4-4557-88e0-7b8cbb3bf8e0.png)

**Comment by csjh** [comment]
Send a screenshot of all your PATH variables, not just the overview. The likely problem is conflicting installations of pip

**Comment by Fourteenloving** [comment]
![image](https://user-images.githubusercontent.com/91829251/135778785-b788528d-4f50-439f-b87f-7ca57e8da376.png)

**Comment by csjh** [comment]
Send the user variables PATH as well

**Comment by Fourteenloving** [comment]
![image](https://user-images.githubusercontent.com/91829251/135781684-b08d76fd-ec7b-4525-a31f-3fd312faa93d.png)

**Comment by csjh** [comment]
Ok then write `python` which should open a python shell, then write `import sys`, enter, `sys.path` and take a screenshot of what that returns

**Comment by Fourteenloving** [comment]
![image](https://user-images.githubusercontent.com/91829251/135784413-8c0955ab-c76b-4901-a044-f0dd0dcac6c5.png)

**Comment by csjh** [comment]
Delete the Microsoft store version

**Comment by Fourteenloving** [comment]
I re-downloaded 3.7.8 after deleting 3.9.7, installed pip, then re-ran and met this.
![image](https://user-images.githubusercontent.com/91829251/135788516-5c610852-310c-4b7a-933b-226276e5d993.png)

**Comment by csjh** [comment]
Ignore what Omitron said, do the regular pip install -r <path to requirements.txt>

**Comment by Fourteenloving** [comment]
![image](https://user-images.githubusercontent.com/91829251/135788791-de520e67-09e9-46a9-b2f6-9f919ac815cd.png)
ok thanks a lot now it's running
