### ISSUE TITLE
dosnt work

### ISSUE THREAD

**Issue by kriule** [csjh/SkyblockSniper#16]

**Comment by kriule** [comment]
just saying pip install -r C:\Downloads\requirements.txt command doesn't exist

**Comment by kriule** [comment]
@csjh @IlmarsXd

**Comment by csjh** [comment]
Look in the “basic troubleshooting part of the readme (for future reference, read the readme before asking questions)

**Comment by kriule** [comment]
yea did it but still not working
@csjh

**Comment by kriule** [comment]
myb we could hop in a dc call and u could help me if u have time i would appreciate it
