### ISSUE TITLE
its just giving me more problems

### ISSUE THREAD

**Issue by kriule** [csjh/SkyblockSniper#18]
C:\Users\User>pip install -r C:\Downloads\requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'C:\\Downloads\\requirements.txt'  welll pls help (and file are in downloads

**Comment by csjh** [comment]
Is requirements.txt in C:\Downloads, or is it in Downloads? The Downloads folder is not always directly in C:\

**Comment by kriule** [comment]
in regular

**Comment by csjh** [comment]
What do you mean "in regular"

**Comment by kriule** [comment]
it was in normal downloads now its in c: downloads but still same thing pops up

**Comment by kriule** [comment]
idk myb when u have time we could hop in discord and u might help me if thats ok with u

**Comment by csjh** [comment]
Send a screenshot of C:\Downloads and show me a screenshot of the error you're getting

**Comment by kriule** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/91843824/135771370-c9cc7038-c89e-46ed-a33a-4696b430df7a.png)

**Comment by kriule** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/91843824/135771390-635cc383-e5eb-4397-91ca-f84957128918.png)

**Comment by csjh** [comment]
Just like the error tells you verbatim, you are missing the -r flag

**Comment by kriule** [comment]
1 sec leme try

**Comment by kriule** [comment]
hey are u still here @csjh

**Comment by kriule** [comment]
ive got 1 more problem

**Comment by kriule** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/91843824/135771618-12f8ab66-eb78-48a9-827c-0e7b702848d6.png)
![Screenshot_4](https://user-images.githubusercontent.com/91843824/135771620-f7326f83-c249-463a-9630-6ec2f0b99380.png)

**Comment by csjh** [comment]
You are trying to run a folder

As mentioned in the how to use, you should have a path directly to SkyblockSniper.py

**Comment by kriule** [comment]
is it gonna trigger u if i ask how to do that?

**Comment by kriule** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/91843824/135771747-4d0ec9c3-e59d-43d5-851e-009e44c20734.png)
wich 1 out of these all

**Comment by kriule** [comment]
im sorry that im soo anoying im just super interested

**Comment by kriule** [comment]
and is ok if it says cannot view auction to every auction

**Comment by kriule** [comment]
or myb i need booster coockie

**Comment by csjh** [comment]
Just follow the How to Use...

**Comment by kriule** [comment]
Yea but i cannot view any auctions

**Comment by kriule** [comment]
like i cannot see ANY

**Comment by kriule** [comment]
and its not saying not found its sayin that i cant view this auction

**Comment by kriule** [comment]
@csjh  pls last 1

**Comment by kriule** [comment]
im fine
