### ISSUE TITLE
is this the exact command i should be writing before i do this?

### ISSUE THREAD

**Issue by clocktickingzZz** [csjh/SkyblockSniper#22]
C:\Users\anonymous>pip install r- C:\Users\Anonymous\Desktop\SkyblockSniper-main\requirements.txt

**Comment by clocktickingzZz** [comment]
when i press enter for that it tells me this Fatal error in launcher: Unable to create process using '"c:\users\anonymous\appdata\local\programs\python\python38\python.exe"

**Comment by clocktickingzZz** [comment]
and then at the end it tells me it cannot find the file specified

**Comment by TheRealOmitron** [comment]
do
>pip install pandas
>pip install requests
>pip install plyer
try doing that

**Comment by clocktickingzZz** [comment]
like instead of pip install -r i do pip install pandas, requests or plyer?

**Comment by clocktickingzZz** [comment]
oh and also at the end of the command it says install plyer C:\Users\Anonymous\Desktop\SkyblockSniper-main\requirements': The system cannot find the file specified

**Comment by csjh** [comment]
requirements isn’t the file, requirements.txt is

**Comment by clocktickingzZz** [comment]
i tried .txt says the same thing :/

**Comment by clocktickingzZz** [comment]
really want it to work but this is really confusing me

**Comment by csjh** [comment]
Google the error and try the solutions there

**Comment by clocktickingzZz** [comment]
oh and is there any reason having python 3.9 be a prblem?

**Comment by clocktickingzZz** [comment]
?

**Comment by clocktickingzZz** [comment]
been at this for hours nothing yet :/
