### ISSUE TITLE
not making very much money on each flip

### ISSUE THREAD

**Issue by KaizDoodle** [csjh/SkyblockSniper#27]
Is there a way to make a minimum price that the items have to be before they are registered in the system

**Comment by csjh** [comment]
Change the LOWEST_PRICE constant on line 27

**Comment by KaizDoodle** [comment]
how do i do that though like how and where do i write it

**Comment by csjh** [comment]
Open SkyblockSniper.py in notepad, go to line 27, change the number that LOWEST_BIN is equal to to whatever number you want the minimum second lowest BIN to be
