### ISSUE TITLE
ModuleNotFoundError: No module named they are being so much like how many i have to install ????

### ISSUE THREAD

**Issue by ibrahim123x** [csjh/SkyblockSniper#28]

**Comment by ibrahim123x** [comment]
should i just keep downloading ?
it is happening in every line tell now line 11 and line 12 and line 13 have this problem should i just keep downloading ?
this happens when i run the command python C:\bla\bla\bla\SkyblockSniper.py

**Comment by csjh** [comment]
As mentioned in the README, the issues category is not for basic Python troubleshooting.
