### ISSUE TITLE
error in code 3 

### ISSUE THREAD

**Issue by gabathus** [csjh/SkyblockSniper#31]
im not good at coding and the vid linked is not very good doesn't teach much and some code is just there with no explanation but i get this error code can i get some help got rid of the start cos my name is in it 
![image](https://user-images.githubusercontent.com/92211153/136655455-edae1552-a6fc-43f2-bfee-e52101612f80.png)
SyntaxError: unexpected character after line continuation character

**Comment by csjh** [comment]
Run it in cmd, not Python shell. Also unzip the zipped download first.
