### ISSUE TITLE
Wall of red text when running "pip install -r C:\Users\lukea\Downloads\SkyblockSniper-main\SkyblockSniper-main\requirements.txt"

### ISSUE THREAD

**Issue by ifibeatuurbad** [csjh/SkyblockSniper#33]
Here are screen shots of the beginning and the end of the error message

![image](https://user-images.githubusercontent.com/92269239/136707235-c35fb165-ab23-499f-bae6-f0879e83d69f.png)
![image](https://user-images.githubusercontent.com/92269239/136707246-41d9c3d7-2a2f-4184-a20f-07b273bd8035.png)

**Comment by csjh** [comment]
Read the readme.
