### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by TheFishyZ** [csjh/SkyblockSniper#4]
When I try to do the 3rd step which requires you to run pip install thing in the command prompt then I get error which says:
'pip' is not recognized as an internal or external command, operable program or batch file. idk how to fix.
![pip](https://user-images.githubusercontent.com/90573852/132999372-f5c7bcd4-ca9d-4ba5-a520-d08984f7e80e.png)

**Comment by csjh** [comment]
You need to add the Scripts folder of your Python installation to your system PATH variables.
