### ISSUE TITLE
How do I fix the hundreds of lines of errors?

### ISSUE THREAD

**Issue by pleaseijustwannausetheflipscript** [csjh/SkyblockSniper#50]
title

**Comment by csjh** [comment]
If you’re going to ignore the first line of the readme at least give screenshots of the problem

**Comment by pleaseijustwannausetheflipscript** [comment]
![image](https://user-images.githubusercontent.com/93489641/139600344-b549f21a-00cb-4dda-b903-caad82954c78.png)
![image](https://user-images.githubusercontent.com/93489641/139600385-a6fe0581-2d75-49f7-aed5-c255d3e5a9ed.png)
![image](https://user-images.githubusercontent.com/93489641/139600439-985e0179-8f35-4899-b6ce-30674d4e46fd.png)
![image](https://user-images.githubusercontent.com/93489641/139600473-0d4eac79-3de9-423c-9c57-7d25ddd66a0e.png)
![image](https://user-images.githubusercontent.com/93489641/139600513-43fad2ca-9b6c-404b-a159-f447e1d20214.png)
![image](https://user-images.githubusercontent.com/93489641/139600557-c16c2748-16f3-4807-aa55-58afb1871541.png)
![image](https://user-images.githubusercontent.com/93489641/139600606-4724e3d7-c5c4-42b1-ba58-25bcb4a2a070.png)
![image](https://user-images.githubusercontent.com/93489641/139600671-cf75ec7b-9eb6-4788-bb15-3f457835c250.png)
![image](https://user-images.githubusercontent.com/93489641/139600699-88986b17-617b-4a14-aac9-3a9a10f6e1c0.png)
![image](https://user-images.githubusercontent.com/93489641/139600743-1cf78f85-56fe-4bf0-9a4f-e665198c0c05.png)
![image](https://user-images.githubusercontent.com/93489641/139600766-b4343335-2f0d-4f8c-bbb1-697f1e26cd93.png)
How do I google this

**Comment by csjh** [comment]
Use Python 3.7.8, as is very very very very clearly stated in the readme :D

**Comment by pleaseijustwannausetheflipscript** [comment]
jesus im stupid
