### ISSUE TITLE
Invalid Syntax in requirements.txt

### ISSUE THREAD

**Issue by nmfcds** [csjh/SkyblockSniper#51]
C:\Users\drews>python C:\Users\****\Desktop\SkyblockSniper-main\requirements.txt
  File "C:\Users\*****\Desktop\SkyblockSniper-main\requirements.txt", line 1
    requests==2.25.1
                   ^
SyntaxError: invalid syntax

-------------

Recently updated to windows 11, I tried reinstalling.

ty

**Comment by csjh** [comment]
Read the README
