### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheRealOmitron** [csjh/SkyblockSniper#7]
ModuleNotFoundError: No module named 'pandas'
ModuleNotFoundError: No module named 'winsound'

**Comment by csjh** [comment]
1. Did you run requirements.txt download
2. Are you on mac?

**Comment by TheRealOmitron** [comment]
i'm on mac and don't know how to run

**Comment by csjh** [comment]
> i'm on mac and don't know how to run

remove import winsound and the line that uses it
